##################################################
## kernel update and reboot
##################################################
- name: kernel update
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - kernel
    - kernel-devel
    - kernel-headers
    - kernel-tools
    - kernel-tools-libs
  register: kernelchange
- name: wait 5 second and reboot
  reboot:
  when: kernelchange is changed
##################################################
## disable SELinux, firewalld, swap
##################################################
- name: permissive SELinux
  selinux:
    policy: targeted
    state: permissive
  register: selinuxchange
- name: wait 5 second and reboot
  reboot:
  when: selinuxchange is changed
- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
- name: turn off swap
  shell: |
    swapoff /dev/dm-1
    systemctl daemon-reload
##################################################
## synchronizing NFS and locale settings
##################################################
- name: delete default nfs server
  replace:
    dest: /etc/chrony.conf
    regexp: '^(server \d+.centos.pool.ntp.org iburst)'
    replace: '# \1'
- name: add nict nfs server
  blockinfile:
    dest: /etc/chrony.conf
    state: present
    content: |

      # ntp servers
      server ntp.jst.mfeed.ad.jp iburst
      server ntp.nict.jp iburst
- name: restart chronyd
  service:
    name: chronyd
    state: started
    enabled: yes
- name: adjust the time
  shell: chronyc -a makestep
  changed_when: false
- name: update-locale
  shell: "localectl set-locale LANG=ja_JP.UTF-8"
- name: timedatectl
  shell: timedatectl set-timezone Asia/Tokyo
- name: set locale in bash
  shell: echo 'export LANG=ja_JP.UTF-8' >> /home/vagrant/.bashrc
