- name: Kubernetes provision common
  hosts: all
  gather_facts: false
  become: true
  pre_tasks:
    - name: install Python3 (required by Ansible)
      raw: /usr/bin/apt-get install -y python3
      changed_when: false
    - name: gather facts
      setup:
  roles:
    - setup
    - docker
    - kubernetes

- name: Kubernetes provision master
  hosts: master
  gather_facts: true
  become: true
  roles:
    - master

- name: Kubernetes provision workers
  hosts: workers
  gather_facts: true
  become: true
  roles:
    - worker
