- name: reset kubeadm
  command: kubeadm reset -f
- name: include kubeadm join variables
  include_vars: ./kubeadm-join.yaml
- name: kubeadm join
  command: "{{ join_command }}"
- name: change DNS IP setting
  replace:
    dest: /var/lib/kubelet/config.yaml
    regexp: '10.96.0.10'
    replace: "{{ cluster_dns }}"
- name: restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
